### ISSUE TITLE
Tokenization issue when trying pretraining a monolingual model from scratch

### ISSUE THREAD

**Issue by gorka96** [prajdabre/yanmtt#4]
Hi and thanks for your amazing work @prajdabre ! 

I got the same error as in https://github.com/prajdabre/yanmtt/issues/2 while trying to train a monolingual BART from scratch for Basque language (eu) using an already existing BERT tokenizer. 

`
python3 pretrain_nmt.py -n 1  -nr 0 -g 1 --model_path models/bart_model --tokenizer_name_or_path ixa-ehu/berteus-base-cased --langs eu --mono_src train.eu --encoder_layers 1 --decoder_layers 1 --encoder_attention_heads=1 --decoder_attention_heads=1 --encoder_ffn_dim=128 --decoder_ffn_dim=128 --d_model=64 --shard_files`

```
.
.
.
 File "/home/BART/yanmtt/bartenv/lib/python3.6/site-packages/transformers-4.3.2-py3.6.egg/transformers/tokenization_utils.py", line 336, in <genexpr>
    for token in tokenized_text
TypeError: _tokenize() takes 2 positional arguments but 5 were given
```

you can get a small monolingual text file from  [opus](opus.nlpl.eu/download.php?f=OpenSubtitles/v2018/mono/OpenSubtitles.raw.eu.gz) if you wanna give it a try.

I also tried to run it using my own output files ( _.vocab and _.model ) from the sentencepiece I trained from my corpus. But I need to provide a a config.json file for the training, which is not clear what it should look like when you want to pretrain a new model from scratch.

Could you help me understand what I am missing to pretrain a monolingual model from scratch properly?

Thanks,

Gorka

**Comment by prajdabre** [comment]
Hi,

Thanks for using my toolkit.

The error you face is because of the type of tokenizer you are using. My code is designed to use two types of tokenizers: AlbertTokenizer or MBartTokenizer. However what you are trying to use is a BertTokenizer which is not possible with my code as it is not designed to use this tokenizer. The BertTokenizer's tokenize function takes 2 positional arguments whereas the MBartTokenizer and AlbertTokenizer takes 5. Note that I have modified the AlbertTokenizer and MBartTokenizer code to enable stochastic tokenization. This means I pass additional arguments which is the reason why there are 5 arguments. (Originally these needed only 2 arguments as well)

So this is what I suggest: 

1. Hard: find a way to convert the BertTokenizer into either an AlbertTokenizer or MBartTokenizer.
2. Easy: Create your own AlbertTokenizer or MBartTokenizer and use it.
3. Medium: Modify the BertTokenizer code (or the tokenizer class code applicable to your tokenizer) and pass dummy arguments corresponding to the additional arguments that tokenization_utils.py expects in line 336.

As for pretraining a model from scratch you dont need a config.json file. Please let me know the part of the code which demands a config file and I'll help you out.

Hope this helps.
Ask me anything.

**Comment by gorka96** [comment]
Thanks for the quick response! I will check your suggestions and come back with more questions if I have any.
